<Project>
  <Import Project="$(MSBuildThisFileDirectory)Version.props" />

  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSource>true</EmbedUntrackedSource>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <RepositoryUrl>https://github.com/rinkink/razorlight</RepositoryUrl>
	<PackageProjectUrl>https://github.com/rinkink/razorlight</PackageProjectUrl>
	<RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>